---
title: इस स्प्राइट को आपकी आवश्यकता है
hero_image: images/banner.png
description:
  - Create a virtual pet, character, or nature simulation that the user can
  - interact with to help it.
meta_title: Scratch coding projects for kids and teens | This sprite needs you
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a virtual pet you can interact with in Scratch.
version: 4
listed: true
copyedit: false
last_tested: "2021-03-26"
steps:
  - 
    title: You will make
  - 
    title: आपका विचार
  - 
    title: निर्माण और परीक्षण करें
    completion:
      - engaged
      - internal
  - 
    title: Checklist
    completion:
      - external
  - 
    title: अपने प्रोजेक्ट को अपग्रेड करें
  - 
    title: शेयर करें
  - 
    title: आगे क्या?
