---
title: هذا الكائن يحتاجك
hero_image: images/banner.png
description:
  قم بإنشاء حيوان أليف افتراضي أو شخصية أو محاكاة طبيعية يمكن للمستخدم التفاعل معها لمساعدتها.
version: 4
listed: true
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: سوف تصنع
  - title: فكرتك
  - title: بناء واختبار
    completion:
      - engaged
      - internal
  - title: قائمة تدقيق
    completion:
      - external
  - title: قم بترقية او تطوير مشروعك
  - title: مشاركة