---
title: Ten duszek cię potrzebuje
hero_image: images/banner.png
description:
  - Utwórz wirtualnego zwierzaka, postać lub symulację natury, z którą użytkownik może
  - wchodzić w interakcję, aby mu pomóc.
meta_title: Projekty programistyczne Scratch dla dzieci i młodzieży | Ten duszek cię potrzebuje
meta_description: Naucz się programować w języku Scratch dzięki projektom programistycznym Fundacji Raspberry Pi dla dzieci i nastolatków. Stwórz animację historii z niespodzianką.
version: 4
listed: true
copyedit: false
last_tested: "2021-03-26"
steps:
  - 
    title: What you will make
  - 
    title: Twój pomysł
  - 
    title: Buduj i testuj
    completion:
      - engaged
      - internal
  - 
    title: Lista kontrolna
    completion:
      - external
  - 
    title: Challenge
    challenge: true
  - 
    title: Udostępnij
  - 
    title: What can you do now?
