---
title: Αυτό το αντικείμενο σε χρειάζεται
hero_image: images/banner.png
description:
  - Δημιούργησε ένα εικονικό κατοικίδιο, χαρακτήρα ή προσομοίωση φύσης με το οποίο ο χρήστης μπορεί να
  - αλληλεπιδράσει για να το βοηθήσει.
meta_title: Έργα κώδικα σε Scratch για παιδιά και εφήβους | Αυτό το αντικείμενο σε χρειάζεται
meta_description: Μάθε να προγραμματίζεις με Scratch με τα έργα κώδικα του Ιδρύματος Raspberry Pi για παιδιά και εφήβους. Δημιούργησε ένα εικονικό κατοικίδιο με το οποίο μπορείς να αλληλεπιδράς στη Scratch.
version: 4
listed: true
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Τι θα φτιάξεις
  - title: Η ιδέα σου
  - title: Δημιουργία και έλεγχος
    completion:
      - engaged
      - internal
  - title: Λίστα ελέγχου
    completion:
      - external
  - title: Αναβάθμιση του έργου σου
  - title: Κοινοποίηση