---
title: Ce sprite a besoin de toi
hero_image: images/banner.png
description: Créer une simulation virtuelle d'animal de compagnie, de personnage ou de nature avec laquelle l'utilisateur peut interagir pour l'aider.
version: 4
listed: true
copyedit: false
last_tested: '2021-03-26'
steps:
  - 
    title: Introduction
  - 
    title: Ton idée
  - 
    title: Construire et tester
    completion:
      - engaged
      - internal
  - 
    title: Réflexion
    completion:
      - external
  - 
    title: Améliorer ton projet
  - 
    title: Partager
  - 
    title: Et ensuite ?
